version: "3.9"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    command:
      - /bin/sh
      - -c
      - |
        alembic upgrade head
        uvicorn --host 0.0.0.0 --port 80 --reload app.main:app
    volumes:
      - ./api:/home/api/
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  db:
    container_name: db-test-task
    image: postgres:15.2-alpine
    volumes:
      - db_test_task:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "no"


volumes:
  db_test_task:
    name: db_test_task